#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -rf 0.0* 1* 2* 3* 4* 5* 6* 7* 8* 9* log* post* 0.*


#------------------------------------------------------------------------------
