#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
grep -e '^titer'  log | awk '{print $2,FS,$3,FS,$4,FS,$5}' > residuals.txt
gnuplot plotumax
#cat umax.txt
gnuplot<<EOF
set term dumb
set xlabel "t"
set xtics out
set ytics out
set yrange [0:310]
plot "residuals.txt" u 1:2 pt '*' notitle
EOF

gnuplot<<EOF
set term dumb
set xlabel "t"
set xtics out
set ytics out
#set yrange [0:310]
plot "residuals.txt" u 1:3 pt '*' title "g",\
	 "residuals.txt" u 1:4 pt 'x' title "u"
EOF

gnuplot<<EOF
set term postscript color enhanced eps font "Times-Roman, 22" 
set output "stokes_3D_residuals.eps" 

lineSize=2.5
set style line 10 dt 1 lw lineSize lc rgb "red" 
set style line 20 dt 1 lw lineSize lc rgb "blue" 

set xlabel "t [s]"
set ylabel "res"

set key reverse spacing 1.4 Left samplen 1.5 top right box
#set logscale x
set logscale y

#set ytics 0,0.2,1
#set mytics 2

#set xtics 0,2,10
#set mxtics 2

#set xrange [0:0.2]
#set yrange [0.8:1.7]

set format y "%.1e"


plot "residuals.txt" u 1:3 w l ls 10 title "{/Symbol G}",\
	 "residuals.txt" u 1:4 w l ls 20 title "u"
EOF