#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

rm -rf constant/faMesh

rm -rf constant/extendedFeatureEdgeMesh

rm -rf constant/triSurface/*.eMesh

rm -rf constant/triSurface/*.stl  constant/triSurface/*.obj

#------------------------------------------------------------------------------
