#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

for i in cpw*
do
	echo $i
	(cd $i && ./Allrun > log &)
done

#------------------------------------------------------------------------------